# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9385fdc3ab5f47cf08cbe542aa0f926aa9fab3f7165cc6b925fd33265d065f060091b191e488baf6a1b6122ef2422ebafa5dd2b939143d01467876a48b2425d

test:
  secret_key_base: cbaa0473ecbde2cf3c531f2446afab96ad45501de2545c85e6e61159ffca90c66089ae3fec2445384cc56584c0f107edddb0253d6c20c7eedab71437599c6e66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
